version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.envs/.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.postgres

volumes:
  postgres_data: