# Generated by Django 4.1.7 on 2023-02-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_todolist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2023-02-25'),
        ),
    ]
